<a href="https://colab.research.google.com/github/sharmaraja/120-Data-Science-Interview-Questions/blob/master/InterviewPrep_DF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataframe Manipulation:

*   string operation
*   replace, where
*   merge and sort and pivot
*   appply, lamdda, map on df
*   loc and iloc

In [ ]:
# fill nulls in sales columns of a dataframe having date and sales, with avg(sales) of that particular year
# In titanic dataset check if the name starts with 'A' and print those records

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = [1,2,3,4,5]
print([i*2 for i in a])

[2, 4, 6, 8, 10]

In [ ]:

data = {'Product_ID':['A','A','A','B','B','C','C','C'],'Sales':[100,150,120,80,90,200,180,220]}
df = pd.DataFrame(data)
# #find the product id with maximum sales.
print(df['Product_ID'][df['Sales']==df['Sales'].max()])

7    C
Name: Product_ID, dtype: object

In [ ]:
d = {'int':a,'sq_a':[i*i for i in a],'cube_a':[i**3 for i in a]}
df = pd.DataFrame(d)
df.head()

   int  sq_a  cube_a
0    1     1       1
1    2     4       8
2    3     9      27
3    4    16      64
4    5    25     125

In [ ]:
data = {'A':np.linspace(0,5,num=5),'B':np.arange(5,10)}
df1 = pd.DataFrame(data)
df1

      A  B
0  0.00  5
1  1.25  6
2  2.50  7
3  3.75  8
4  5.00  9

In [ ]:
df['col3'] = ['Rajat Sharma','Sharma Rajat','Raj Shar','Shar Raja','one two']
df.head()

   col1  col2          col3
0     1     1  Rajat Sharma
1     4     8  Sharma Rajat
2     9    27      Raj Shar
3    16    64     Shar Raja
4    25   125       one two

In [ ]:
df[['first_name', 'last_name']] = df['col3'].str.split(' ', expand=True)
df.head()

   col1  col2          col3 first_name last_name
0     1     1  Rajat Sharma      Rajat    Sharma
1     4     8  Sharma Rajat     Sharma     Rajat
2     9    27      Raj Shar        Raj      Shar
3    16    64     Shar Raja       Shar      Raja
4    25   125       one two        one       two

**Loc and iloc**

In [ ]:
# loc is label of index based indexing df.loc[1] will give row where index=1
# iloc is integer based indexing irrespective of their labels df.iloc[1] will give 1st row index whatever be the value
# Used for looping over the dataframe-computationaly very expensive

In [ ]:
print('loc\n',df['col3'].loc[2],'\niloc\n',df['col3'].iloc[4])
# as index value and index number are same we get same results

loc
 Raj Shar
iloc
 one two

In [ ]:
df.index = ['a','b','c','d','e']
df.head()

   col1  col2          col3 first_name last_name
a     1     1  Rajat Sharma      Rajat    Sharma
b     4     8  Sharma Rajat     Sharma     Rajat
c     9    27      Raj Shar        Raj      Shar
d    16    64     Shar Raja       Shar      Raja
e    25   125       one two        one       two

In [ ]:
print('loc\n',df['col3'].loc['a'],'\niloc\n',df['col3'].iloc[1])

loc
 Rajat Sharma
iloc
 Sharma Rajat

In [ ]:
# df.iloc[row,col], (x:) means from x(incl) till end && (:x) from begin till x(not incl)
df.iloc[:,2:]

           col3 first_name last_name
a  Rajat Sharma      Rajat    Sharma
b  Sharma Rajat     Sharma     Rajat
c      Raj Shar        Raj      Shar
d     Shar Raja       Shar      Raja
e       one two        one       two

**Iterrows and itertuples**

In [ ]:
for ind, val in df.iterrows():
  if val[2] == 'Rajat Sharma':
    print(ind,val[2])

a Rajat Sharma

<ipython-input-20-4537ba7bd2c9>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if val[2] == 'Rajat Sharma':
<ipython-input-20-4537ba7bd2c9>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ind,val[2])

In [ ]:
# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve','check'],
        'Age': [25, 30, 35, 40, 45,59]}
df = pd.DataFrame(data)

# Define bin edges and labels
bins = [0, 30, 40, 50]  # Bin edges
labels = ['Young', 'Middle-aged', 'Old']  # Bin labels

# Apply `cut` to create a new column 'Age Group'
df['Age Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

df

      Name  Age    Age Group
0    Alice   25        Young
1      Bob   30        Young
2  Charlie   35  Middle-aged
3    David   40  Middle-aged
4      Eve   45          Old
5    check   59          NaN

In [ ]:
df['AG'] = df['Age'].apply(lambda x: 'Young' if x<=30 else 'Mid' if 30<x<=40 else 'Old')
df

      Name  Age    Age Group     AG
0    Alice   25        Young  Young
1      Bob   30        Young  Young
2  Charlie   35  Middle-aged    Mid
3    David   40  Middle-aged    Mid
4      Eve   45          Old    Old
5    check   59          NaN    Old

In [ ]:
# Sample DataFrame
data = {
    'Name': ['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'David Miller', 'Eve Adams'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data)
df.head()

            Name         City
0  Alice Johnson     New York
1      Bob Smith  Los Angeles
2  Charlie Brown      Chicago
3   David Miller      Houston
4      Eve Adams      Phoenix

In [ ]:
df[['First_name','Last_name']] = df['Name'].str.split(' ',expand=True)
df.head()

            Name         City First_name Last_name
0  Alice Johnson     New York      Alice   Johnson
1      Bob Smith  Los Angeles        Bob     Smith
2  Charlie Brown      Chicago    Charlie     Brown
3   David Miller      Houston      David    Miller
4      Eve Adams      Phoenix        Eve     Adams

In [ ]:
df['Conatins_Alice'] = df['Name'].str.contains('Alice')
# df[df['City']].str.removeprefix()
df.head()

            Name         City First_name Last_name  Conatins_Alice
0  Alice Johnson     New York      Alice   Johnson            True
1      Bob Smith  Los Angeles        Bob     Smith           False
2  Charlie Brown      Chicago    Charlie     Brown           False
3   David Miller      Houston      David    Miller           False
4      Eve Adams      Phoenix        Eve     Adams           False

In [ ]:
import pandas as pd

# Sample dataset
data = {
    'Region': ['East', 'East', 'West', 'West', 'North', 'North', 'South', 'South'],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [234, 150, 210, 120, 345, 200, 500, 420],
    'Quantity': [10, 15, 8, 12, 11, 16, 9, 14]
}

df = pd.DataFrame(data)
df.head()

  Region Product  Sales  Quantity
0   East       A    234        10
1   East       B    150        15
2   West       A    210         8
3   West       B    120        12
4  North       A    345        11

In [ ]:
df_summ = df.groupby(by=['Region','Product']).agg({'Sales':'sum','Quantity':'mean'})
df_summ.head(15)

                Sales  Quantity
Region Product
East   A          234      10.0
       B          150      15.0
North  A          345      11.0
       B          200      16.0
South  A          500       9.0
       B          420      14.0
West   A          210       8.0
       B          120      12.0

In [ ]:
# Merge and Join
df_1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C', 'D', 'E', 'F']},
                    index=[0, 1, 2, 3])

df_2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['G', 'H', 'I', 'J']},
                    index=[4, 5, 6, 7])

In [ ]:
df_3 = pd.merge(df_1, df_2, how='outer', on='A')
df_3.head()

    A  B_x  C_x  B_y  C_y
0  A0  NaN  NaN   B0    C
1  A1  NaN  NaN   B1    D
2  A2  NaN  NaN   B2    E
3  A3  NaN  NaN   B3    F
4  A4   B4    G  NaN  NaN

In [ ]:
# Pivot table with multiple indices
pivot_table_multi_index = pd.pivot_table(df,
                                         values=['Sales', 'Quantity'],
                                         index=['Region', 'Product'],
                                         aggfunc={'Sales': 'sum', 'Quantity': 'mean'},
                                         fill_value=0)

print(pivot_table_multi_index)

                Quantity  Sales
Region Product
East   A            10.0    234
       B            15.0    150
North  A            11.0    345
       B            16.0    200
South  A             9.0    500
       B            14.0    420
West   A             8.0    210
       B            12.0    120

In [ ]:
d = {'id':[1,2,3],
     'name':['Cooler', 'Facewash','Lays FOOD'],
     'Sector':['Electronics','Consumer Durable','Eatable']}
df = pd.DataFrame(d)
df.head()

   id       name            Sector
0   1     Cooler       Electronics
1   2   Facewash  Consumer Durable
2   3  Lays FOOD           Eatable

In [ ]:
df['code'] = df['Sector'].apply(lambda x: 'ELEC' if x=='Electronics' else 'CD' if x=='Consumer Durable' else 'FOOD' if x=='Eatable' else 'NA')
df.head()

   id       name            Sector  code
0   1     Cooler       Electronics  ELEC
1   2   Facewash  Consumer Durable    CD
2   3  Lays FOOD           Eatable  FOOD

In [ ]:
df['code_map'] = df['Sector'].map(lambda x: 'ELEC' if x=='Electronics' else 'CD' if x=='Consumer Durable' else 'FOOD' if x=='Eatable' else 'NA')
df.head()

   id       name            Sector  code code_map
0   1     Cooler       Electronics  ELEC     ELEC
1   2   Facewash  Consumer Durable    CD       CD
2   3  Lays FOOD           Eatable  FOOD     FOOD

In [ ]:
df['code_where'] = ''
df['code_where'] = np.where(df['Sector']=='Electronics', 'ELEC', df['code_where'])
df['code_where'] = np.where(df['Sector']=='Consumer Durable', 'CD', df['code_where'])
df['code_where'] = np.where(df['Sector']=='Eatable', 'Food', df['code_where'])

df.head()

   id       name            Sector  code code_map code_where
0   1     Cooler       Electronics  ELEC     ELEC       ELEC
1   2   Facewash  Consumer Durable    CD       CD         CD
2   3  Lays FOOD           Eatable  FOOD     FOOD       Food

In [ ]:
df['code_repl'] = df['Sector'].replace('Electronics','ELEC')
df['code_repl'] = df['code_repl'].replace('Consumer Durable','CD')
df['code_repl'] = df['code_repl'].replace('Eatable','FOOD')
df.head()

   id       name            Sector  code code_map code_repl   bool code_where
0   1     Cooler       Electronics  ELEC     ELEC      ELEC   true       ELEC
1   2   Facewash  Consumer Durable    CD       CD        CD  false         CD
2   3  Lays FOOD           Eatable  FOOD     FOOD      FOOD   true       Food

In [ ]:
df['bool'] = ['true','false','true']

df.head()

   id       name            Sector  code code_map code_repl   bool
0   1     Cooler       Electronics  ELEC     ELEC      ELEC   true
1   2   Facewash  Consumer Durable    CD       CD        CD  false
2   3  Lays FOOD           Eatable  FOOD     FOOD      FOOD   true

In [ ]:
# Group and Merge