<a href="https://colab.research.google.com/github/sharmaraja/120-Data-Science-Interview-Questions/blob/master/Interview_Prepare_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Interview Basic Questions
***
***

## To Do:
***
***
    1) Theoritical Questions for Python Basic
    2) Tuples, Dictionary, Lists, Sets, Golbal variables
    3) Functions
    4) Break and Continue
    5) Error Handling
    6) Lambda, Map, Fillter, Reduce
    7) List comprehension, Terninary Operators
***

### Dictionary

In [ ]:
rollNumbers =[122,233,353,456]
names = ['alex','bob','can', 'don']
dict1 = dict(zip(rollNumbers,names))

In [ ]:
# delete items from dictionary
del dict1[122]

In [ ]:
dict1.keys()

dict_keys([122, 233, 353, 456])

In [ ]:
dict1.values()

dict_values(['alex', 'bob', 'can', 'don', 'kon'])

In [ ]:
dict1.update({'120':'kon'})
dict1.items()

dict_items([(233, 'bob'), (353, 'can'), (456, 'don'), ('120', 'kon')])

In [ ]:
for i in dict1.keys():
  print(i)

122
233
353
456
120

Nested dictionary

In [ ]:
import pandas as pd

# Sample data with multiple records
nested = [
    {
        "person": {
            "name": "John",
            "age": 30,
            "address": {
                "street": "123 Main St",
                "city": "New York",
                "zip": "10001"
            },
            "hobbies": ["reading", "cycling"]
        },
        "company": {
            "name": "Tech Corp",
            "location": {
                "city": "San Francisco",
                "state": "CA"
            },
            "employees": 500
        }
    },
    {
        "person": {
            "name": "Alice",
            "age": 25,
            "address": {
                "street": "456 Oak Ave",
                "city": "Boston",
                "zip": "02108"
            },
            "hobbies": ["painting", "swimming"]
        },
        "company": {
            "name": "Data Inc",
            "location": {
                "city": "Chicago",
                "state": "IL"
            },
            "employees": 300
        }
    }
]

In [ ]:
# Convert nested dictionary to DataFrame
df = pd.json_normalize(nested)
df.head()

,person.name,person.age,person.address.street,person.address.city,person.address.zip,person.hobbies,company.name,company.location.city,company.location.state,company.employees
0,John,30,123 Main St,New York,10001,"[reading, cycling]",Tech Corp,San Francisco,CA,500
1,Alice,25,456 Oak Ave,Boston,02108,"[painting, swimming]",Data Inc,Chicago,IL,300

In [ ]:
# Post-process: Convert lists (e.g., hobbies) to comma-separated strings
df['person.hobbies'] = df['person.hobbies'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)
df.head()

,person.name,person.age,person.address.street,person.address.city,person.address.zip,person.hobbies,company.name,company.location.city,company.location.state,company.employees
0,John,30,123 Main St,New York,10001,"reading,cycling",Tech Corp,San Francisco,CA,500
1,Alice,25,456 Oak Ave,Boston,02108,"painting,swimming",Data Inc,Chicago,IL,300

In [ ]:
nested[1]

{'person': {'name': 'Alice',
  'age': 25,
  'address': {'street': '456 Oak Ave', 'city': 'Boston', 'zip': '02108'},
  'hobbies': ['painting', 'hiking']},
 'company': {'name': 'Innovate Ltd',
  'location': {'city': 'Chicago', 'state': 'IL'},
  'employees': 200}}

In [ ]:
['person','age','address','street','city','zip','hobbies','company','location','city','state','employees']

In [ ]:
# Flatten nested dictionary and convert to DataFrame
def flatten_dict(d, parent_key='', sep='_'):
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep).items())
        elif isinstance(v, list):
            items.append((new_key, ', '.join(v)))
        else:
            items.append((new_key, v))
    return dict(items)

In [ ]:
# Process all records
flattened_data = [flatten_dict(record) for record in nested]
flattened_data

[{'person_name': 'John',
  'person_age': 30,
  'person_address_street': '123 Main St',
  'person_address_city': 'New York',
  'person_address_zip': '10001',
  'person_hobbies': 'reading, cycling',
  'company_name': 'Tech Corp',
  'company_location_city': 'San Francisco',
  'company_location_state': 'CA',
  'company_employees': 500},
 {'person_name': 'Alice',
  'person_age': 25,
  'person_address_street': '456 Oak Ave',
  'person_address_city': 'Boston',
  'person_address_zip': '02108',
  'person_hobbies': 'painting, hiking',
  'company_name': 'Innovate Ltd',
  'company_location_city': 'Chicago',
  'company_location_state': 'IL',
  'company_employees': 200}]

In [ ]:
df = pd.DataFrame(nested)
df.head()

,person,company
0,"{'name': 'John', 'age': 30, 'address': {'stree...","{'name': 'Tech Corp', 'location': {'city': 'Sa..."
1,"{'name': 'Alice', 'age': 25, 'address': {'stre...","{'name': 'Innovate Ltd', 'location': {'city': ..."

In [ ]:
temp

{'person': {0: {'name': 'John',
   'age': 30,
   'address': {'street': '123 Main St', 'city': 'New York', 'zip': '10001'},
   'hobbies': ['reading', 'cycling']},
  1: {'name': 'Alice',
   'age': 25,
   'address': {'street': '456 Oak Ave', 'city': 'Boston', 'zip': '02108'},
   'hobbies': ['painting', 'hiking']}},
 'company': {0: {'name': 'Tech Corp',
   'location': {'city': 'San Francisco', 'state': 'CA'},
   'employees': 500},
  1: {'name': 'Innovate Ltd',
   'location': {'city': 'Chicago', 'state': 'IL'},
   'employees': 200}}}

In [ ]:
# Create DataFrame
df = pd.DataFrame(flattened_data)
df.head()

,person_name,person_age,person_address_street,person_address_city,person_address_zip,person_hobbies,company_name,company_location_city,company_location_state,company_employees
0,John,30,123 Main St,New York,10001,"reading, cycling",Tech Corp,San Francisco,CA,500
1,Alice,25,456 Oak Ave,Boston,02108,"painting, hiking",Innovate Ltd,Chicago,IL,200

In [ ]:
data[0]['person']['address']

{'street': '123 Main St', 'city': 'New York', 'zip': '10001'}

In [ ]:
nested.values()

dict_values([{'name': 'John', 'age': 30, 'address': {'street': '123 Main St', 'city': 'New York', 'zip': '10001'}, 'hobbies': ['reading', 'cycling']}, {'name': 'Tech Corp', 'location': {'city': 'San Francisco', 'state': 'CA'}, 'employees': 500}])

In [ ]:
nested.items()

TypeError: 'dict_items' object is not callable

In [ ]:
import pandas as pd
df = pd.DataFrame(nested)
df

,person,company
name,John,Tech Corp
age,30,NaN
address,"{'street': '123 Main St', 'city': 'New York', ...",NaN
hobbies,"[reading, cycling]",NaN
location,NaN,"{'city': 'San Francisco', 'state': 'CA'}"
employees,NaN,500

In [ ]:
d1 = {1: {'roll': '101', 'name': 'sam'}, 2: {'roll': '102', 'name': 'ram'}}
d1

{1: {'roll': '101', 'name': 'sam'}, 2: {'roll': '102', 'name': 'ram'}}

In [ ]:
d1[1]['roll']

'101'

In [ ]:
l =  [1, 'a', 2, 'b', 3, 'c']
d={}
for ind,val in enumerate(l):
  if ind%2==0:
    d[val]=l[ind+1]

print(d)

{1: 'a', 2: 'b', 3: 'c'}

In [ ]:
l_tp = list(d.items())
l_tp

[(1, 'a'), (2, 'b'), (3, 'c')]

In [ ]:
l1 = list(d.keys()) + list(d.values())
l1

[1, 2, 3, 'a', 'b', 'c']

In [ ]:
x = list(d.keys())
print(x)
y = list(d.values())
print(y)
for i in y:
      x.append(i)
print(x)

[1, 2, 3]
['a', 'b', 'c']
[1, 2, 3, 'a', 'b', 'c']

In [ ]:
l1 = [11,32,3]
l2 = ['a','b','c']
d1 = dict(zip(l1,l2))
d1

{11: 'a', 32: 'b', 3: 'c'}

In [ ]:
l1.sort()

In [ ]:
l1

[3, 11, 32]

In [ ]:
dict1 = {2: 'Apple', 1:'Mango', 3:'Orange', 4:'Banana'}
dict1

{2: 'Apple', 1: 'Mango', 3: 'Orange', 4: 'Banana'}

In [ ]:
print(sorted(dict1.keys()))

[1, 2, 3, 4]

In [ ]:
dict1

{2: 'Apple', 1: 'Mango', 3: 'Orange', 4: 'Banana'}

In [ ]:
for key in sorted(dict1,reverse=True):
      print("Sorted dictionary using key:",(key, dict1[key]))

Sorted dictionary using key: (4, 'Banana')
Sorted dictionary using key: (3, 'Orange')
Sorted dictionary using key: (2, 'Apple')
Sorted dictionary using key: (1, 'Mango')

In [ ]:
# l1_s = l1.sort()
# l1
# Both these methods work
print(sorted(l1))
l1

[3, 11, 32]

In [ ]:
d[1]='a'
d[2]='b'
d[5] = 'five'
d

{1: 'a', 2: 'b', 3: 'c', 5: 'five'}

### Copy v/s Deep Copy

In [ ]:
a = [10, 20, 30]
b = copy.deepcopy(a)

NameError: name 'copy' is not defined

### Global Variables

In [ ]:
global_var = 10

def global_view():
    print('Global Variable value: ',global_var)

def modify_global():
    '''We need to call gloabl variable inorder to edit it'''
    global global_var
    global_var = 20


def modify():
  print('in the modify function')
  global_var = 30

global_view()

modify_global()

global_view()

# As we didn't call the global variable its not modified
modify()

global_view()

Global Variable value:  10
Global Variable value:  20
in the modify function
Global Variable value:  20

### Backlashes

In [ ]:
print('ab','b','c')
# gives a space by default

ab b c

In [ ]:
print('abs\nabss\\nabsss')

abs
abss\nabsss

In [ ]:
str1 = 'ha'
str2 = str1*5
print(str2)

hahahahaha

### Slicing List

list_slice = list[start:stop:step]

In [ ]:
l = [1,2,3,4,5,6,7,8,9]

In [ ]:
print('Reverse: ',l[::-1],'\nEvery second: ',l[::2])

Reverse:  [9, 8, 7, 6, 5, 4, 3, 2, 1]
Every second:  [1, 3, 5, 7, 9]

In [ ]:
l[1:7:2]

[2, 4, 6]

In [ ]:
l1 = l[::2]
l1

[3, 5, 7, 9]

In [ ]:
my_list = [11,12,13,14,15]
your_list = my_list[1:-1]
print(your_list)
# It will start from index 1 and avoid the index -1 i.e., 15

[12, 13, 14]

In [ ]:
print(my_list[::-1])
# the step size here is -1, which is only possible when we start from the end i.e., greatest index

[15, 14, 13, 12, 11]

In [ ]:
print('Print\'Print\'')

Print'Print'

In [ ]:
tup = (1,2,3,4)
print(type(tup),type(tup[0]))

<class 'tuple'> <class 'int'>

In [ ]:
tup_1 = tup+(5,)
print(tup_1,end='\n\n')
tup_2 = tup * 2
print(tup_2,end='\n\n')

(1, 2, 3, 4, 5)

(1, 2, 3, 4, 1, 2, 3, 4)

### Terninary Operators

In [ ]:
to_check = 6
msg = "Even" if to_check%2 == 0 else "Odd"
print(msg)

Even

### Error Handling

In [ ]:
def error_hand(a,b):
    '''Return a/b'''
    try:
        # Code that may raise an exception
        x = a/b  # This will raise a "ZeroDivisionError"
        print(a/b)
    except ZeroDivisionError as e:
        # Handling the specific exception
        print("An error occurred:", e)
    except Exception as e:
        # Handling a more general exception (if needed)
        print("A different error occurred:", e)
    else:
        # Code to execute if no exception was raised
        print("No exceptions occurred.")
    finally:
        # Code to execute whether there was an exception or not
        print("This code block always runs.")

In [ ]:
error_hand(1,0)

An error occurred: division by zero
This code block always runs.

In [ ]:
error_hand(10,1)

No exceptions occurred.
This code always runs.

In [ ]:
u='u'
error_hand(10,u)

A different error occurred: unsupported operand type(s) for /: 'int' and 'str'
This code block always runs.

In [ ]:
1/0

ZeroDivisionError: division by zero

### Lambda, Map, Filter, Reduce

### Lambda

In [ ]:
x = 'sls'
res = lambda x: 1 if x==x[::-1] else 0
print(res(x))

1

In [ ]:
max_func = lambda x,y : x if x>=y else y
val = max_func(2,6)
print(val)

6

In [ ]:
even_func = lambda x : 1 if x%2==0 else 0
val = even_func(55)
print(val)

0

In [ ]:
square_func = lambda x : x**3
val = square_func(4)
print(val)

64

In [ ]:
x=1
ans = lambda x: 'True' if x**.5==int(x**.5) else 'False'

print(ans(x))

True

### Map

new = map(func, iterator)

In [ ]:
l = [1,2,3,4,5]
l_sq = list(map(square_func,l))
l_sq

[1, 8, 27, 64, 125]

In [ ]:
l_alp = ['sat', 'bat', 'cat', 'mat']

In [ ]:
list(l_alp[0])

['s', 'a', 't']

In [ ]:
l_alp = ['sat', 'bat', 'cat', 'mat']

# map() can listify the list of strings individually
test = list(map(list, l_alp))
print(test)

[['s', 'a', 't'], ['b', 'a', 't'], ['c', 'a', 't'], ['m', 'a', 't']]

### Filter

filterd_list = filter(funct, iterator)

In [ ]:
l = [1,2,3,4,5,6,7,8,9]
l_filt = list( filter( even_func, l) )
print(l_filt)

[2, 4, 6, 8]

In [ ]:
l = [1,2,3,4,5,6,7,8,9]
l_filt = list( filter( lambda x : 1 if x>5 else 0, l) )
print(l_filt)

[6, 7, 8, 9]

### Reduce

In [ ]:
import functools

# initializing list
lis = [1, 3, 5, 6, 2]

# using reduce to compute sum of list
print("The sum of the list elements is : ", end="")
print(functools.reduce(lambda a, b: a+b, lis))

# using reduce to compute maximum element from list
print("The maximum element of the list is : ", end="")
print(functools.reduce(lambda a, b: a if a > b else b, lis))

The sum of the list elements is : 17
The maximum element of the list is : 6

### Factorial Reccurssion

In [ ]:
def fact(n):
#     using While
#     while n>1:
#         return(n*fact(n-1))
#     return(1)

# using If-else
    if n==1:
        return(1)
    else:
        return(n*fact(n-1))

In [ ]:
factorial = fact(5)
print(factorial)

120

### Sum of List Numbers

In [ ]:
def sum_list(l):
    if len(l)==1:
        return l[0]
    else:
        return(l[0]+sum_list(l[1:]))

In [ ]:
l=[1,2,3,4,5]
print(sum_list([1,2,3,4,5]))

15

In [ ]:
l=[1,2,3,4,5,6,7,8]
l_sq = list(map(lambda x:x**2, l))
print(l_sq)

[1, 4, 9, 16, 25, 36, 49, 64]

In [ ]:
l=[1,2,3,4,5,6,7,8]
l_even = list(filter(lambda x: 1 if x%2==0 else 0, l))
l_even

[2, 4, 6, 8]

In [ ]:
cond = lambda x,y: y/x if x<y else x/y
print(round(cond(7,13),2))

1.86

In [ ]:
l_even = [i for i in l if i%2==0]
l_even_sq = [i**2 for i in l if i%2==0]
print(l_even,l_even_sq)

[2, 4, 6, 8] [4, 16, 36, 64]

List Comprehension

In [ ]:
l1=['abc','pqr','xyz']
l2=['abc','pqr','mno']
l3=[i for i in (l1+l2) if (i not in l1 or i not in l2)]
l3

['xyz', 'mno']

In [ ]:
l=[1,2,3,4,5,6,6,7,8,9]
l_e = [i for i in l if i%2==0]
l_e_s = [i**2 for i in l if i%2==0]
l_o = [i for i in l if i%2!=0]
print(l_e,'\n',l_e_s,'\n',l_o)

[2, 4, 6, 6, 8]
 [4, 16, 36, 36, 64]
 [1, 3, 5, 7, 9]

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = [x.upper()+' Fruit' for x in fruits if 'a' in x ]

# Syntax
# newlist = [output/transformed output for (value in iterator) in (list to iterate) if (condition)]

print(newlist)

['APPLE Fruit', 'BANANA Fruit', 'MANGO Fruit']

In [ ]:
newlist = [x if x != "banana" else "orange" for x in fruits]
newlist

['apple', 'orange', 'cherry', 'kiwi', 'mango']

In [ ]:
# Reverse each string in a tuple
List = [string[::-1] for string in ('Geeks', 'for', 'Geeks')]

# Display list
print(List)

['skeeG', 'rof', 'skeeG']

In [ ]:
names = ["G", "G1", "g"]
ages = [25, 30, 35]
person_tuples = [(name, age) for name, age in zip(names, ages)]
print(person_tuples, type(person_tuples))

[('G', 25), ('G1', 30), ('g', 35)] <class 'list'>

In [ ]:
test_keys = ["Rash", "Kil", "Varsha"]
test_values = [1, 4, 5]
res = {test_keys[i]: test_values[i] for i in range(len(test_keys))}
print(res,type(res))

{'Rash': 1, 'Kil': 4, 'Varsha': 5} <class 'dict'>

In [ ]:
d=dict(zip(names,ages))
print(d)

{'G': 25, 'G1': 30, 'g': 35}

In [ ]:
txt = "I like bananas"

txt = txt.replace(" ", "")

# x=txt.split('')

x=list(txt)
x

['I', 'l', 'i', 'k', 'e', 'b', 'a', 'n', 'a', 'n', 'a', 's']

RegEx

In [ ]:
import re

In [ ]:
string = "The quick brown fox jumps over the lazy dog"
pattern = "[a-m]"
result = re.findall(pattern, string)
print(result)

['h', 'e', 'i', 'c', 'k', 'b', 'f', 'j', 'm', 'e', 'h', 'e', 'l', 'a', 'd', 'g']

**Sorting and Searching**

In [ ]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    print('Using bubble sort\n',arr)

In [ ]:
def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_idx = i
        for j in range(i+1, n):
            if arr[j] < arr[min_idx]:
                min_idx = j
        arr[i], arr[min_idx] = arr[min_idx], arr[i]
    print('Using selection sort\n',arr)

In [ ]:
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    print('Insertion sort\n',arr)

**Merge and Quick Sort**

Referencing Memory

In [ ]:
x = 10
y = x
print(id(x),'\n',id(y))

133085716496912
 133085716496912

In [ ]:
x = 20
print(id(x),'\n',id(y))

# string, tuple, or integer--> immutable--> changes in these makes a new object hence new id
# list, dictionary, or set --> mutable --> changes in these does not make a new object but only updates the old one hence same id

133085716497232
 133085716496912

Key Points:



*   Variables store references to objects in memory.
*   Assigning a variable to another variable creates another reference to the same object.
*   Reassigning a variable can create a new object and update the variable's reference.
*   Modifying mutable objects (like lists) through a reference modifies the original object.

In [ ]:
a = 'Rajat sharma'
a_lst = a.split(" ")
a_lst

['Rajat', 'sharma']

In [ ]:
a_lttr = list(a)
a_lttr

['R', 'a', 'j', 'a', 't', ' ', 's', 'h', 'a', 'r', 'm', 'a']

In [ ]:
a1, a2 = a.split(' ')
a_reve = a2[::-1] + ' ' + a1[::-1]
a_reve

'amrahs tajaR'

In [ ]:
a_lttr.sort()
print(a_lttr,'\n', a_lttr[::-1])

[' ', 'R', 'a', 'a', 'a', 'a', 'h', 'j', 'm', 'r', 's', 't']
 ['t', 's', 'r', 'm', 'j', 'h', 'a', 'a', 'a', 'a', 'R', ' ']

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
np.delete(arr, 2)

array([1, 2, 4, 5])

In [ ]:
# upper, lower, strip, split, replace

In [ ]:
# Pivot Tables